Added RSS implementation
stjiris/nextjs-jurisprudencia pull request #1
Opened 2024-05-07 09:58 UTC by SobriKeN

No merge conflicts, which is good

2024-05-07 10:12 UTC, diogoalmiro commented on compose/clitools/Dockerfile
> +RUN git clone https://github.com/SobriKeN/jurisprudencia-rss.git && cd jurisprudencia-rss && npm install && npm run build
Update link

2024-05-07 10:13 UTC, diogoalmiro commented on rss.xml
> +<?xml version="1.0" encoding="utf-8"?>
This file should not be commited

2024-05-07 10:15 UTC, diogoalmiro commented on src/pages/api/rss.ts
> +export default async function docApiHandler(
Look at other api routes, I added a Logger.

`export default LoggerApi(async function docApiHandler` (and import LoggerApi)

2024-05-07 10:15 UTC, diogoalmiro commented on Área Criminal.xml
Remove this file

2024-05-07 10:15 UTC, diogoalmiro commented on Área Cível.xml
Remove this file

2024-05-07 10:15 UTC, diogoalmiro commented on Área Social.xml
Remove this file

2024-05-07 10:16 UTC, diogoalmiro requested changes
Check inline comments

2024-05-08 08:30 UTC, SobriKeN commented
Changes made, please check

2024-05-08 11:53 UTC, merged